sudo: false
language: python

matrix:
  include:
    - python: 2.6
      env:
        - DJANGO_VERSION=1.4
        - NOSE_VERSION=1.2
        - IGNORE_FLAKE8=1
    - python: 2.6
      env:
        - DJANGO_VERSION=1.5
        - NOSE_VERSION=1.2
        - IGNORE_FLAKE8=1
    - python: 2.7
      env:
        - DJANGO_VERSION=1.4
        - NOSE_VERSION=1.2
    - python: 2.7
      env:
        - DJANGO_VERSION=1.5
        - NOSE_VERSION=1.2
    - python: 2.7
      env:
        - DJANGO_VERSION=1.6
        - NOSE_VERSION=1.2
    - python: 2.7
      env:
        - DJANGO_VERSION=1.7
        - NOSE_VERSION=1.4.4
    - python: 2.7
      env:
        - DJANGO_VERSION=1.8
        - NOSE_VERSION=1.4.4
    - python: 2.7
      env:
        - DJANGO_VERSION=1.9
        - NOSE_VERSION=1.4.4
    - python: 2.7
      env:
        - DJANGO_VERSION=1.10
        - NOSE_VERSION=1.4.4
    - python: 2.7
      env:
        - DJANGO_VERSION=1.11
        - NOSE_VERSION=1.4.4
    - python: 3.4
      env:
        - DJANGO_VERSION=1.6
        - NOSE_VERSION=1.2
    - python: 3.4
      env:
        - DJANGO_VERSION=1.7
        - NOSE_VERSION=1.4.4
    - python: 3.4
      env:
        - DJANGO_VERSION=1.8
        - NOSE_VERSION=1.4.4
    - python: 3.4
      env:
        - DJANGO_VERSION=1.9
        - NOSE_VERSION=1.4.4
    - python: 3.4
      env:
        - DJANGO_VERSION=1.10
        - NOSE_VERSION=1.4.4
    - python: 3.4
      env:
        - DJANGO_VERSION=1.11
        - NOSE_VERSION=1.4.4
    - python: 3.5
      env:
        - DJANGO_VERSION=1.8
        - NOSE_VERSION=1.4.4
    - python: 3.5
      env:
        - DJANGO_VERSION=1.9
        - NOSE_VERSION=1.4.4
    - python: 3.5
      env:
        - DJANGO_VERSION=1.10
        - NOSE_VERSION=1.4.4
    - python: 3.5
      env:
        - DJANGO_VERSION=1.11
        - NOSE_VERSION=1.4.4
    - python: 3.6
      env:
        - DJANGO_VERSION=1.11
        - NOSE_VERSION=1.4.4

install:
 - pip install -U pip
 - pip install -q --no-binary Django Django==$DJANGO_VERSION
 - pip install -q django-nose==$NOSE_VERSION
 - pip install -q coverage==3.7.1
 - pip install -q flake8

script:
 - if ! [ $IGNORE_FLAKE8 ]; then flake8 global_permissions; fi;
 - python runtests.py
